program Holmes;

uses
  Vcl.Forms,
  MAIN in 'MAIN.pas' {FMAIN},
  MSPLASH in 'MODULS\SERV\MSPLASH.pas' {FSPLASH},
  MCLOSE in 'MODULS\SERV\MCLOSE.pas' {FCLOSE},
  MVAR_OLE_EDIT in 'MODULS\VAR\MVAR_OLE_EDIT.pas' {FVAR_OLE_EDIT},
  FunConst in 'MODULS\CONST\FunConst.pas',
  FunSys in 'Fun\FunSys.pas',
  FunType in 'Fun\FunType.pas',
  FunText in 'Fun\FunText.pas',
  FunVcl in 'Fun\COMMON\FunVcl.pas',
  FunIni in 'Fun\FunIni.pas',
  FunInfo in 'Fun\COMMON\FunInfo.pas',
  FunFiles in 'Fun\COMMON\FunFiles.pas',
  FunBD in 'Fun\FunBD.pas',
  FunDay in 'Fun\COMMON\FunDay.pas',
  FunList in 'Fun\COMMON\FunList.pas',
  FunIDE in 'Fun\FunIDE.pas',
  FunStream in 'Fun\COMMON\FunStream.pas',
  FunTree in 'Fun\COMMON\FunTree.pas',
  FunOle in 'Fun\COMMON\FunOle.pas',
  FunWord in 'Fun\COMMON\FunWord.pas',
  FunClip in 'Fun\COMMON\FunClip.pas',
  FunDecoder in 'MODULS\SERV\DECODER\FunDecoder.pas',
  FunPadeg in 'MODULS\SERV\PADEG\FunPadeg.pas',
  PadegFIO_ANSI in 'MODULS\SERV\PADEG\PadegFIO_ANSI.pas',
  FunVerify in 'MODULS\SERV\VERIFY\FunVerify.pas',
  MVerify in 'MODULS\SERV\VERIFY\MVerify.pas' {FVerify},
  FunBDList in 'MODULS\SERV\BDLIST\FunBDList.pas',
  MBDLIST in 'MODULS\SERV\BDLIST\MBDLIST.pas' {FBDList},
  FunMemo in 'MODULS\SERV\MEMO\FunMemo.pas',
  MMEMO in 'MODULS\SERV\MEMO\MMEMO.pas' {FMEMO},
  MUD in 'MODULS\UD\MUD.pas' {FUD},
  MDOC in 'MODULS\DOC\MDOC.pas' {FDOC},
  MDOC_NEW in 'MODULS\DOC\MDOC_NEW.pas' {FDOC_NEW},
  MDOC_PROP in 'MODULS\DOC\MDOC_PROP.pas' {FDOC_PROP},
  MVAR in 'MODULS\VAR\MVAR.pas' {FVAR},
  MVAR_EDIT in 'MODULS\VAR\MVAR_EDIT.pas' {FVAR_EDIT},
  MVAR_MEMO in 'MODULS\VAR\MVAR_MEMO.pas' {FVAR_MEMO},
  MVAR_DATE in 'MODULS\VAR\MVAR_DATE.pas' {FVAR_DATE},
  MVAR_EXPERT in 'MODULS\VAR\MVAR_EXPERT.pas' {FVAR_EXPERT},
  MVAR_EXPERT_HELPER in 'MODULS\VAR\EXPERT_HELPER\MVAR_EXPERT_HELPER.pas' {FVAR_EXPERT_HELPER},
  MVAR_REST in 'MODULS\VAR\MVAR_REST.pas' {FVAR_REST},
  MVAR_REST_EDIT in 'MODULS\VAR\MVAR_REST_EDIT.pas' {FVAR_REST_EDIT},
  MVAR_REST_ADD in 'MODULS\VAR\MVAR_REST_ADD.pas' {FVAR_REST_ADD},
  MVAR_SELECT in 'MODULS\VAR\MVAR_SELECT.pas' {FVAR_SELECT},
  MVAR_OLE in 'MODULS\VAR\MVAR_OLE.pas' {FVAR_OLE},
  MVAR_UD in 'MODULS\VAR\MVAR_UD.pas',
  MVAR_UD_EDIT_PPERSON in 'MODULS\VAR\UD_EDIT\MVAR_UD_EDIT_PPERSON.pas' {FVAR_UD_EDIT_PPERSON},
  MVAR_UD_EDIT_LPERSON in 'MODULS\VAR\UD_EDIT\MVAR_UD_EDIT_LPERSON.pas' {FVAR_UD_EDIT_LPERSON},
  MVAR_UD_EDIT_DPERSON in 'MODULS\VAR\UD_EDIT\MVAR_UD_EDIT_DPERSON.pas' {FVAR_UD_EDIT_DPERSON},
  MVAR_UD_EDIT_OBJECT in 'MODULS\VAR\UD_EDIT\MVAR_UD_EDIT_OBJECT.pas' {FVAR_UD_EDIT_OBJECT},
  MDECOD_OLE in 'MODULS\SERV\DECODER\MDECOD_OLE.pas' {FDECOD_OLE},
  MOLE in 'MODULS\SERV\OLE\MOLE.pas' {FOLE},
  MFREE in 'MODULS\SERV\MFREE.pas' {FFREE},
  MPASS in 'MODULS\SERV\MPASS.pas' {FPASS},
  FunArt in 'MODULS\ART\FunArt.pas',
  MCOM in 'MODULS\ART\MCOM.pas' {FCOM},
  MSTRUCT in 'MODULS\STRUCT\MSTRUCT.pas' {FSTRUCT},
  MABOUT in 'MODULS\SERV\MABOUT.pas' {FABOUT},
  FunRx in 'Fun\COMMON\FunRx.pas',
  FunOutlook in 'Fun\COMMON\FunOutlook.pas',
  FunDateTimePicker in 'Fun\COMMON\FunDateTimePicker.pas',
  MSET in 'MODULS\SET\MSET.pas' {FSET},
  FunWait in 'MODULS\SERV\WAIT\FunWait.pas',
  MWAIT in 'MODULS\SERV\WAIT\MWAIT.pas' {FWait},
  MUK in 'MODULS\ART\MUK.pas' {FUK},
  FunRichEdit in 'Fun\COMMON\FunRichEdit.pas';

{$R *.res}

begin
  Application.Initialize;
  //Application.MainFormOnTaskbar := True;
  Application.Title := 'ױמכלס';
  Application.CreateForm(TFMAIN, FMAIN);
  Application.Run;
end.
